### ISSUE TITLE
Replace the bullet lists with sortable tables

### ISSUE THREAD

**Issue by ErezBiren** [lirantal/awesome-opensource-israel#112]
A solution might be found here:
[https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-conten](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content)

I can take it.

**Comment by UrielOfir** [comment]
You are welcome to solve it :)

**Comment by zivnadel** [comment]
Table sort is not supported in GitHub. The option is to install a userscript in the browser that will allow this, such as what you suggested. However, only the installer will be able to use this feature. If you think its fine, I can arrange the content in a normal markdown table.

**Comment by ErezBiren** [comment]
Since we have now the great site [https://opensource-il.vercel.app/](https://opensource-il.vercel.app/) that reads the data from here, I guess this issue can be closed.
