### ISSUE TITLE
Let Yonatan help us

### ISSUE THREAD

**Issue by UrielOfir** [lirantal/awesome-opensource-israel#164]
HI @lirantal ,
Yonatan (https://github.com/yonatanmgr) is the maintainer of the website that is running about our Readme file - https://opensource-il.vercel.app/.
Can you give him a management role in our repo so he would be able to connect the website and the Readme more easily?

**Comment by lirantal** [comment]
Yes, of course. I sent Yonatan an invite now to the repository.
By the way, the website looks awesome! 🎉
