### ISSUE TITLE
Incorrect Link for "Red Hat" under "Companies" Category

### ISSUE THREAD

**Issue by lielperetz** [lirantal/awesome-opensource-israel#183]
**Issue Description:**

I noticed that in the README file of this repository, specifically under the "Companies" category, there is an entry "Red Hat" that links to the Red Hat website instead of its repository. 

**Expected Behavior:**

The link under the "Red Hat" entry in the "Companies" category should point to the Red Hat repository on GitHub.

**Additional Information:**

- Repository URL: [https://github.com/RedHatOfficial](https://github.com/RedHatOfficial)
- Link in README: [https://github.com/lirantal/awesome-opensource-israel#companies](https://github.com/lirantal/awesome-opensource-israel#companies)

I suggest updating the link to lead to the correct repository page for Red Hat.

**Comment by lirantal** [comment]
Thanks for raising, Liel. Would you want to create a pull request that fixes the issue?

**Comment by lielperetz** [comment]
Sure! Thank you!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
13.09.23,
16:05:57

‫בתאריך יום ד׳, 13 בספט׳ 2023 ב-15:58 מאת ‪Liran Tal‬‏ <‪
***@***.***‬‏>:‬

**Comment by lirantal** [comment]
fixed in #184
