### ISSUE TITLE
Incorrect Link in README Leading to 404 Error for "helm-dashboard-v2"

### ISSUE THREAD

**Issue by lielperetz** [lirantal/awesome-opensource-israel#206]
### Summary/Background:
The README file for the repository contains an incorrect link for the "helm-dashboard-v2" section, resulting in a 404 error when attempting to access the content.

### Steps to Reproduce:
1. Navigate to the README file of the repository.
2. Scroll down to the "helm-dashboard-v2" section.
3. Click on the link associated with "helm-dashboard-v2."

### Expected Behavior:
Clicking on the link for "helm-dashboard-v2" should redirect to the correct repository or page related to the Helm Dashboard v2.

### Actual Behavior:
The current link associated with "helm-dashboard-v2" results in a 404 error page, indicating that the content could not be found.

### Notes:
It seems like the hyperlink might be misspelled or pointing to an outdated repository, resulting in the inability to access the relevant information. I have attempted to access the link on multiple occasions, and the 404 error consistently occurs.

**Comment by lirantal** [comment]
Thanks Liel.
Do you want to fix it? by either removing the link to the helm dashboard entry, or trying to find the actual repository URL

**Comment by lielperetz** [comment]
yes.

**Comment by lirantal** [comment]
Thank you!
