### ISSUE TITLE
Help clear the definitions a bit for me please..

### ISSUE THREAD

**Issue by igalklebanov** [lirantal/awesome-opensource-israel#220]
Hey 👋 

Are projects that are (co-)maintained and/or (co-)led by Israeli/s, but not created by Israelis, relevant here?

**Comment by lirantal** [comment]
I want to say yes to be inclusive of that but I would say to an extent where there's considerable contribution and actually maintained. So yes :-)

**Comment by igalklebanov** [comment]
There are 2 projects like this that I can think of..
`kysely` core (I'm biased obviously 🙃) and `qwik` where Shai Reznik is a top contributor AND leads it nowadays.

**Comment by lirantal** [comment]
All makes sense to me! Let's add
