### ISSUE TITLE
DebConf 20 (Debian conf at Haifa - Aug 2020)

### ISSUE THREAD

**Issue by DekelKan** [lirantal/awesome-opensource-israel#61]
Not sure if it fits the 'Events' category because it's only one time.
but if you wish to add it, I'll be happy to create a PR with the relevant link.

**Comment by lirantal** [comment]
Definitely, please do!

**Comment by DekelKan** [comment]
Created PR #62

**Comment by DekelKan** [comment]
Already merged by you (lirantal) Thank you
