### ISSUE TITLE
Project suggestion

### ISSUE THREAD

**Issue by DekelKan** [lirantal/awesome-opensource-israel#64]
Hi Liran,

I'd like to suggest adding Vue Tables 2  by Matanya to the 'Project' list

[Vue Tables 2](https://github.com/matfish2/vue-tables-2)

**Comment by lirantal** [comment]
Sounds great. Go ahead and PR it? we'll merge away

**Comment by DekelKan** [comment]
Sure. Adding Vue Tables 2 with PR #65
