### ISSUE TITLE
Petri

### ISSUE THREAD

**Issue by Mennaruuk** [lirantal/awesome-opensource-israel#68]
Petri's site is [down](https://wix.github.io/petri). Perhaps it's better to link to the [GitHub repo](https://github.com/wix-incubator/petri) or the [Wayback Machine](https://web.archive.org/web/20200401081618/http://wix.github.io/petri/).

**Comment by Mennaruuk** [comment]
BTW, a wonderful list you're maintaining, thanks!

**Comment by benjamingr** [comment]
Thanks for the PR :]
