### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by dolby360** [lirantal/awesome-opensource-israel#78]
All first links from busmq  up to logrotator are broken

**Comment by lirantal** [comment]
True. Looks like they're all part of the `capriza` org which no longer exists... 
Let's see if we can ping @fujifish who added them and we can update, and on the failure of that we can remove for now.

**Comment by fujifish** [comment]
Unfortunately Capriza was sold off to a 3rd party along with all the rights its assets, including the github repo. When that happened we lost all access to the open source projects. Sometime back they decided to completely delete the capriza org from github and they spread all the repos in an arbitrary manner between various people. 
I managed to find most of them and fork them to https://github.com/fujifish

**Comment by lirantal** [comment]
Thanks for explaining @fujifish. Do you want to shoot in a PR that updates whatever repos you can point to the forks and remove the rest that are gone?
