### ISSUE TITLE
Broken Link: javascript Israel 

### ISSUE THREAD

**Issue by AviramV** [lirantal/awesome-opensource-israel#84]
[JavaScript Israel](http://www.jsisrael.com/) seems to be down, and possibly have been for quite a while (last records on [wayback machine from 2020](https://web.archive.org/web/20201101000000*/jsisrael.com)) .
Maybe consider pointing to the [FB group ](https://www.facebook.com/groups/jsisrael/)or [github](https://github.com/jsIsrael)?

**Comment by benjamingr** [comment]
@shairez

**Comment by lirantal** [comment]
Good catch. Pinged Shai on another platform too.

**Comment by lirantal** [comment]
@AviramV in the meanwhile, I think you can send a PR to update to either or both of the options you listed.

**Comment by shairez** [comment]
Thanks everyone for pointing this out

I'll redirect (on our side) the domain to the facebook group... this should save the need for the PR

It will probably take a few hours for the changes to propagate

**Comment by lirantal** [comment]
Thanks!

**Comment by shairez** [comment]
Done
@lirantal I believe you can close this issue
