### ISSUE TITLE
Could we share israel language open source project?

### ISSUE THREAD

**Issue by padixa** [lirantal/awesome-opensource-israel#88]
Could we share isreal language but maybe not made by Israelis, but maybe more Israelis people could use it for free and increase productivity?

**Comment by lirantal** [comment]
Apologies, I'm not following :D 
Can you explain again?

**Comment by padixa** [comment]
I mean could we share some israel language open source project into you `[awesome-opensource-israel](https://github.com/lirantal/awesome-opensource-israel)` ? but the project not made by Israelis, but might be helpfull for the Israel people.

**Comment by lirantal** [comment]
@padixa how about you give an example so I can better understand what are you referring to?

This repository's original intention is to highlight open source work made by folks who live in Israel and to foster the community and collaboration around it. If it fits that loose definition then why not.

**Comment by padixa** [comment]
@lirantal Yeah, I just worry If I put the link to here, some people maybe not really happy because that project not made by Israelis.

OK. So I recommend : [TradingSystem](https://github.com/oybab/TradingSystem) - A multi-language cross-platform open source free trading system that supports personal transaction management, restaurants, small shops, supermarkets, hotels, etc. It can also support secondary development and cooperate with your current business management and statistical reports.

**Comment by padixa** [comment]
@lirantal That's why I'm asking you, If you only want the open source project which made by people live in Israel, Just never mind. :-)

**Comment by lirantal** [comment]
I think the expectation of what would be relevant was clearly communicated from the [start](https://github.com/lirantal/awesome-opensource-israel/issues/88#issuecomment-1121579846).

**Comment by padixa** [comment]
Ok.
